### ISSUE TITLE
[Question] Is it true that all traffic go through VPN?

### ISSUE THREAD

**Issue by ain-soph** [guillaumedsde/alpine-qbittorrent-openvpn#100]
I know that it should be the case that all traffic go through VPN, but I just noticed that there are quite some data transferred through `eth0` but not through `tun1` (around 7.9GB = 20.4GB - 12.5GB for download, and 6.8GB = 9.1GB - 2.3GB for upload).

Is it normal? I don't think other connections other than qBit could generate so much data.

Just in case I receive any warning mails from my ISP 😂

I'm using NordVPN btw.

![image](https://user-images.githubusercontent.com/13214530/141192805-5e3c4e7a-e871-472a-93df-5a5beeaa4655.png)

**Comment by guillaumedsde** [comment]
hi, I added a VPN killswitch to the docker image, Normally (if I did not mess anything up, feel free to check the code, the more eyeballs on it, the mire sure we can be) the only traffic allowed in the container is through the VPN tunnel.

You can test for leaks using IPLeak torrent IP leak detection:

https://ipleak.net/
