### ISSUE TITLE
"File error alert" | "error: No such device"

### ISSUE THREAD

**Issue by heinsenberg82** [guillaumedsde/alpine-qbittorrent-openvpn#107]
This error is really driving me nuts. I can't figure it out what's happening. I've already checked my permissions (the container user has full access to all my folders), so that's not the issue.

Every torrent I add gets the error status. When I check the logs, this is what I get:

`(N) 2021-12-16T12:33:19 - 'Movie.Name.2021.2160p.WEB-DL.x265.10bit.SDR.DDP5.1-TEPES' added to download list.`
`(W) 2021-12-16T12:33:24 - File error alert. Torrent: "Movie.Name.2021.2160p.WEB-DL.x265.10bit.SDR.DDP5.1-TEPES". File: "/downloads/incomplete/MOVIE.NAME.2021.2160p.WEB-DL.x265.10bit.SDR.DDP5.1-TEPES/MOVIE.NAME.2021.2160p.WEB-DL.DDP5.1.x265-TEPES.mkv". Reason: MOVIE.NAME.2021.2160p.WEB-DL.x265.10bit.SDR.DDP5.1-TEPES file_open (/downloads/incomplete/MOVIE.NAME.2021.2160p.WEB-DL.x265.10bit.SDR.DDP5.1-TEPES/MOVIE.NAME.2021.2160p.WEB-DL.DDP5.1.x265-TEPES.mkv) error: No such device
`

I've checked the path indicated by the error (`/downloads/incomplete/MOVIE.NAME.2021.2160p.WEB-DL.x265.10bit.SDR.DDP5.1-TEPES/MOVIE.NAME.2021.2160p.WEB-DL.DDP5.1.x265-TEPES.mkv`), and it exists. The folder and the files we're created when I added the torrent.

So I have no clue about where to start digging.

**Comment by jsntay** [comment]
Having the exact same issue here. However, with the same set-up and file permissions, the older version (January 2021 Docker image) works perfectly fine.

**Comment by switchboy** [comment]
Having the same issue with another alpine based docker image. So it might be a problem upstream. (use openmediavault and a mergerfs filesystem)

**Comment by jsntay** [comment]
@heinsenberg82 @switchboy Found the solution. This is actually a problem with mergerfs: https://github.com/trapexit/mergerfs#rtorrent-fails-with-enodev-no-such-device. I used the [basic mmap options](https://github.com/trapexit/mergerfs#you-need-mmap-used-by-rtorrent-and-many-sqlite3-base-software), everything works fine after reboot now.

**Comment by zero617** [comment]
> the [basic mmap options](https://github.com/trapexit/mergerfs#you-need-mmap-used-by-rtorrent-and-many-sqlite3-base-software)

how to use the basic mmap options in qbittorent

**Comment by guillaumedsde** [comment]
@zero617 these seem to be mount options, so its probably something you'd define in your fstab file

I'll close this issue as a workaround seems to have been found
