### ISSUE TITLE
Synology Permission Issue

### ISSUE THREAD

**Issue by kylemcdonald87** [guillaumedsde/alpine-qbittorrent-openvpn#12]
The current version(docker) is resetting all user folder permissions for my downloads folder when started.  It changes the folder permission to only allow the docker user access.

**Comment by guillaumedsde** [comment]
> The current version(docker) is resetting all user folder permissions for my downloads folder when started. It changes the folder permission to only allow the docker user access.

this is bad, sorry about that :/ working on a fix right now

**Comment by guillaumedsde** [comment]
should be fixed, once [this CI pipeline](https://gitlab.com/guillaumedsde/alpine-qbittorrent-openvpn/-/pipelines/161224496) finishes, try pulling the `latest` or `python` tag and it won't reset the permissions for the downloads folder, *just the ownership with the given `PUID` and `PGID`*

**Comment by kylemcdonald87** [comment]
Will do.. I'll keep you updated.

**Comment by kylemcdonald87** [comment]
Ran into this.. When starting it blanks out my openvpn-credentials.txt file.. I've copied it a few times and it overwrites it I believe.

**Comment by guillaumedsde** [comment]
> Ran into this.. When starting it blanks out my openvpn-credentials.txt file.. I've copied it a few times and it overwrites it I believe.

hi, yes you're meant to set `OPENVPN_USERNAME` and `OPENVPN_PASSWORD` with the environment variables (the container then copies them into a file for openvpn to use)

**Comment by kylemcdonald87** [comment]
Gotcha... Will test shortly

**Comment by kylemcdonald87** [comment]
Good to go! Thanks for the quick response/fix.

**Comment by guillaumedsde** [comment]
any time ;)
