### ISSUE TITLE
Need python3 installed - 

### ISSUE THREAD

**Issue by rtb144** [guillaumedsde/alpine-qbittorrent-openvpn#129]
Search tools need Python3.
I've been installing using 'apk add python3 py3-pip' from within the container /bin/bash
Not sure if another version of alpine or adding python3 to dockerfile is best way forward

**Comment by MrBradricks** [comment]
Are you using the :python image tag?
I am and it almost works, some plugins seem to crash the qbittorrent process, or at least cause it to hang. 
I see nothing in the logs. 
Other plugins function properly like "torrents-csv"

**Comment by guillaumedsde** [comment]
@MrBradricks is correct, you need to use the `:python` tagged image that includes python
