### ISSUE TITLE
Permission gets changed in the downloads folder,

### ISSUE THREAD

**Issue by Nephim** [guillaumedsde/alpine-qbittorrent-openvpn#17]
So I've had a few problems with the docker. Im quite new to the whole docker and linux thing. However Ive got it to a semi usable place now. 

1. So I did not know that I needed to pass it a localtion for the config as It is not stated anywhere in the page. So when I ran it without the argument it returned an error passing it the default that u provided created the paths from / which in hindsight is normal behavior i had hopped it would recognize this and keep the configs inside the docker.

2. The downloads variable is not working properly? It's just creating a downloads folder inside the config;/qBittorrent/downloads/
I gave it the argument to have the config in a good position. So I can access it and it isent that big of a deal now would just be nice to have it be placed somewhere else. I also noticed that if I try and change the default save path in the qBittorrent web panel its root folder is the same as the config: 

3. and biggest issue right now for me as I have not found a solution? A umask argument at docker container creation would be really nice. as I really would like a umask with 0775 as ive set the folder up with samba so I can access it from my other machines including windows. Meaning I can delete/change/execute anything from windows without having to ssh and chmoding everything. I could just set up a script to chmod which is quite messy but is fairly easy. Problem is then that the docker is chmodding the config: to 700? and the rest to only read access on the group and guest. I think some folders might be different didnt check all of them. A lot of the reason im having issues is also because im running samba with a different user but in the same group. I know I could easily change this however It would be nice if I could keep it like this and also i feel like it might be more secure atleast in some aspects?

Sorry if you feel like im harping on you I really think this is really well done and youve stripped out so much so it runs amazingly well with high amounts of security and efficiency. English is not my native language so everything I write might not be 100% but i hope you understand me. And you have time to read all of this 

;)

**Comment by guillaumedsde** [comment]
Hi,

1. try mounting the config directory on your host to `/config` in the container
2. try mounting your download directory on your host to `/downloads` in the container
3. its possible `1` and `2` will solve this issue

**Comment by Nephim** [comment]
Thanks ive made some changes to my setup based on your solutions. It works well now thanks.
