### ISSUE TITLE
Issue with Surfshark | Could not find OpenVPN configuration 

### ISSUE THREAD

**Issue by Edortiz101** [guillaumedsde/alpine-qbittorrent-openvpn#21]
Hi, 
First sorry for my bad English, I've an issue with the provider Surfshark, the error is the following :

```
qbittorrent-openvpn    | ERROR: Could not find OpenVPN configuration "FR\" for provider SURFSHARK
qbittorrent-openvpn    | [cont-init.d] 02-setup-openvpn: exited 1.
qbittorrent-openvpn    | [cont-finish.d] executing container finish scripts...
qbittorrent-openvpn    | [cont-finish.d] done.
qbittorrent-openvpn    | [s6-finish] waiting for services.
qbittorrent-openvpn    | [s6-finish] sending all processes the TERM signal.
qbittorrent-openvpn    | [s6-finish] sending all processes the KILL signal and exiting.
```
My  compose configuration : 
  image: guillaumedsde/alpine-qbittorrent-openvpn:latest
  container_name: qbittorrent-openvpn
  restart: unless-stopped
  environment:
   - OPENVPN_PROVIDER=SURFSHARK
   - OPENVPN_CONFIG=FR\
   - PUID=${PUID}
   - PGID=${PGID}
   - LAN=192.168.0.0/16
   - OPENVPN_USERNAME=
   - OPENVPN_PASSWORD=
  cap_add:
   - NET_ADMIN
  ports:
   - '8080:8080'
  volumes:
   - ${PATH_QBT}:/config
   - ${PATH_MEDIA}:/data
`
I did some research in the closed issue but I couldn't find a solution. 
Any help is welcome, and thanks in advance. 
Regards,

**Comment by guillaumedsde** [comment]
I think there might be an error in your config for: `OPENVPN_CONFIG=FR\` I think that you need to put in a valid config name (like `fr-par_udp` for example)

**Comment by svloosbroek** [comment]
I had a similar problem, all the config files for your provider are automatically downloaded from https://github.com/haugene/docker-transmission-openvpn.git/trunk/openvpn/${lowercase_openvpn_provider} and then the .ovpn extension is added to it. So look up the config files for your provider in the other github project, omit the .ovpn extension and you have your config line.

**Comment by TheCatster** [comment]
That address is no longer found, I'm having the same exact issue. Is this possibly a bug? The url now seems to be [](https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/surfshark). This occurs for my other VPN providers as well (namely Windscribe and PIA).

**Comment by guillaumedsde** [comment]
I've implemented a fix, see my comment here: https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/33#issuecomment-725339440 let me know if that fixes the issue for you ;)

**Comment by guillaumedsde** [comment]
I'll close this issue, but feel free to reopen if the fix mentionned above doesnt work :)
