### ISSUE TITLE
Old verstion of qBittorrent?

### ISSUE THREAD

**Issue by Nephim** [guillaumedsde/alpine-qbittorrent-openvpn#31]
This is more of a question.. 

Is there a reason as to why its still running v4,2.5 of qBittorrent?

4.3.0.1 is out 👍

**Comment by guillaumedsde** [comment]
Hi, I've been testing version 4.3.0.1 on my personal setup for a couple days to test if it was stable, I'll merge it when I find some time, in the meantime, the `development` tag on dockerhub has version 4.3.0.1 if you want to try it 🙂

**Comment by Nephim** [comment]
Cool, Ill just wait till it gets to main. But thanks for the info and now ive got something to look forward to 👍 

Great job on this docker btw!

**Comment by guillaumedsde** [comment]
upgraded in 6b74919
