### ISSUE TITLE
"Unauthorized" upon connecting to the web interface

### ISSUE THREAD

**Issue by 0ze** [guillaumedsde/alpine-qbittorrent-openvpn#32]
## Information

_describe the issue_

![](https://i.imgur.com/WCjOUMM.png)

when trying to connect to the web interface, it just says Unauthorized. am i connecting to the wrong ip? feeling dumb. also, when I tried to use OPENVPN_PROVIDER as PIA, i couldnt get it to find any of the configs like US Chicago, US Texas, etc. yes, I properly escaped the spaces.

## Current setup

_information about your current setup_

using a custom openvpn config, but its just generated from pia openvpn config generator tool. replaced sensitive info with &'s, but thats the exact run command im using. I changed the LAN to 10.0.0.0 from 192.168.0.0 since thats the format my lan uses. 

## `docker-compose.yml` file or `docker run` command

_how did you start the container?_ (don't forget to use backticks for creating a proper code block)

```
docker run --cap-add=NET_ADMIN -d \
              -v /home/&&/ten/media/dl:/downloads \
              -v /home/&&/ten/media/tc:/config \
	      -v /home/&&/ten/media/tf:/torrents \
              -v /etc/localtime:/etc/localtime:ro \
	      --name qbit-vpn \
              -e OPENVPN_USERNAME=&&&&&&  \
              -e OPENVPN_PASSWORD=&&&&&& \
              -e PUID=1000 \
              -e PGID=1000 \
              -e LAN=10.0.0.0/16 \
              -p 8089:8080 \
              guillaumedsde/alpine-qbittorrent-openvpn:latest
```

## Attempted Fix(es)

_What you have tried in order to fix the issue_ (if anything)

changed openvpn config, run command, different browser, even calling curl/wget from the server running the docker container also results in the "unauthorized" response

**Comment by cllu** [comment]
The solution in https://github.com/qbittorrent/qBittorrent/issues/8095#issuecomment-472740702 works for me.

**Comment by 0cj** [comment]
> 

> The solution in [qbittorrent/qBittorrent#8095 (comment)](https://github.com/qbittorrent/qBittorrent/issues/8095#issuecomment-472740702) works for me.

edited my config and it works now, thank you so much

**Comment by 0ze** [comment]
> The solution in [qbittorrent/qBittorrent#8095 (comment)](https://github.com/qbittorrent/qBittorrent/issues/8095#issuecomment-472740702) works for me.

edited my config and it works perfectly now, thank you so much

**Comment by shuffleznl** [comment]
For posterity; Decentraleyes chrome-extension also results in 'Unauthorized'.
Private browsing or whitelisting in extension worked for me.

**Comment by tamarindmonkey** [comment]
You are probably passing a referrer in your Request headers.
General -> Referrer Policy: strict-origin-when-cross-origin

Set:
WebUI\CSRFProtection=false

I couldn't care less about this stupid feature when I'm running qbittorrent on my LAN and nobody else could possibly get to it. Really dumb that they don't present these options in the settings in the client but whatever

**Comment by spencerthayer** [comment]
> You can change the setting in the WebUI under Options -> Enable Cross-Site Request Forgery (CSRF) protection. Uncheck it.

Thank you!
