### ISSUE TITLE
Bad download speed?

### ISSUE THREAD

**Issue by cyrilghl** [guillaumedsde/alpine-qbittorrent-openvpn#51]
Hi!

I disable all limits and settings like that in qbitvpn, but i'm stuck at 2.3 2.7 MB/s, maybe it could be torrents but I choose torrent which have more than 50 peers! With transmission-haugene-openvpn, I get a 25 MB/s speed constantly, is this an issue? What can I send to help?

Thanks,

Babeyoda

**Comment by guillaumedsde** [comment]
hum, its hard to tell because transmission is a diferrent torrent client, can you reproduce this issue on qbittorrent outside of a docker container and over a VPN?

**Comment by tnunamak** [comment]
I have also observed slow speeds in alpine-qbittorrent-openvpn. I ran speedtest-cli inside of the container while connected to VPN, and did the same thing, using the same OpenVPN config in transmission-haugene-openvpn, and saw 5-10x faster speeds.

**Comment by cyrilghl** [comment]
Well, when I changed the openvpn config (I was on Switzerland and I switched to Paris), I get 70 Mb/s so it's okay for me!
