### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gmillerd** [guillaumedsde/alpine-qbittorrent-openvpn#52]
## Information

Run external program on torrent completion is extremely fragile (static compile?) and crashes qbittorrent.

## Current setup

_information about your current setup_

python 8eeac62e227d

## `docker-compose.yml` file or `docker run` command

_how did you start the container?_ (don't forget to use backticks for creating a proper code block)

```IMG=guillaumedsde/alpine-qbittorrent-openvpn:python

docker run \
       --name "bt" \
       --rm \
       --cap-add=NET_ADMIN \
       -v /bt/xfers:/downloads \
       -v /bt/config:/config \
       -v /etc/localtime:/etc/localtime:ro \
       -e OPENVPN_PROVIDER= \
       -e OPENVPN_CONFIG=default \
       -e OPENVPN_USERNAME="REDACTED" \
       -e OPENVPN_PASSWORD="REDACTED" \
       -e PUID=1000 \
       -e PGID=1000 \
       -e LAN=192.168.0.0/24 \
       -p 8080:8080 \
       $IMG
```

## Attempted Fix(es)

The following script works 1 or 2 times in 10, otherwise it creates defunct qbittorrent-nox processes. Where the process is stalled, killing the younger qbittorent-nox child processes frees up cleanly and qbittorrrent is back via systemctl.

Even a simple script with "date >> /config/log"  for content zombies most of the time.

```
#/bin/sh

# /config/complete.sh "%I" "%R"

set -x

WEBUI="http://localhost:8080/api/v2/torrents"
HASH="$1"
RDIR="$2"

if [ "${HASH}" == "" ]; then exit; fi
if [ "$RDIR" == "" ]; then exit; fi
test ! -e "${RDIR}" && exit

function dl {
    curl --cookie 'SID=REDACTED' "${WEBUI}/$1"
}

if [ -n "${HASH}" ]; then
    dl "resume?hashes=$HASH"
    dl "removeTags?hashes=$HASH"
fi

if [ -n "${HASH}" ]; then
    dl "addTags?tags=syncing&hashes=$HASH"
fi


#
```

**Comment by guillaumedsde** [comment]
Seems like a diuplicate of https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/issues/53 ? feel free to reopen with more details if that's not the case
