### ISSUE TITLE
Question about the OpenVPN tunnel

### ISSUE THREAD

**Issue by Pistrie** [guillaumedsde/alpine-qbittorrent-openvpn#57]
I would leave a comment if github allowed such a thing, but it can't, so I have no other way to ask my question. (If there is and Im just a dumbass, please let me know)

I'm new to docker and the internal functions of a vpn, and I have a question about the internet traffic. Does the OpenVPN traffic only cover the in and output of the docker image, or will all the traffic on my device go through the OpenVPN tunnel?

For example, I have a torrent running on the docker, but I want to download a file from the internet at the same time. Will both downloads go through the tunnel, or just the traffic from the torrent?

**Comment by Pistrie** [comment]
Oops didnt mean to add a bug label. How do I change that?

**Comment by Hukuma1** [comment]
Just the traffic from the docker container/torrent.
