### ISSUE TITLE
More specific mullvad servers?

### ISSUE THREAD

**Issue by tnunamak** [guillaumedsde/alpine-qbittorrent-openvpn#62]
Is it possible to use a configuration different from those listed here: https://github.com/haugene/docker-transmission-openvpn/tree/master/openvpn/mullvad? Mullvad's port forwarding is by city, but none of these configurations allow for specifying a city. Thanks.

**Comment by tnunamak** [comment]
I was able to work around this by providing /config/openvpn/config.ovpn and /etc/openvpn/mullvad/ca.crt and via volumes, and removing the OPENVPN configuration vars ([per the code](https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/blob/229684b7c328c3c03bb661954a68e3cb2c0f2d35/rootfs/etc/cont-init.d/02-setup-openvpn#L32)).

**Comment by guillaumedsde** [comment]
Thanks for the workaround, this container uses Haugene's work on centralizing all VPN configurations, you can indeed provide your own in order to select a specific server
