### ISSUE TITLE
 RTNETLINK answers: File exists /ERROR: Linux route add command failed: external program exited with error status: 2

### ISSUE THREAD

**Issue by friki67** [guillaumedsde/alpine-qbittorrent-openvpn#71]
This is related to issue[ #1142](https://github.com/haugene/docker-transmission-openvpn/issues/1142) in transmission-vpn container, and I think to [#135 ](https://github.com/haugene/docker-transmission-openvpn/issues/135#) too

Container starts as "healthy", but I cannot access qBitTorrent WebUI in 8080.

Logs shows at the end:
```
RTNETLINK answers: File exists
Thu Apr 29 10:43:48 2021 ERROR: Linux route add command failed: external program exited with error status: 2
```
I'm running Debian Buster, kernel 4.19.181-1 x86_64.
I have a WireGuard server running in this machine.

Docker+compose+Portainer. Configured like this:
```
PUID | 1000
PGID | 1000
OPENVPN_PROVIDER | IVACY
OPENVPN_CONFIG | NorwayOsloUDP
OPENVPN_USERNAME | user
OPENVPN_PASSWORD | mypass
LAN | 192.168.100.0/24
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CONFIG_DIR | /config
QBT_SAVE_PATH | /downloads
QBT_WEBUI_PORT | 8080
```
Set the NET_ADMIN capability through the GUI, set the volumes.

ip r
```
default via 192.168.100.1 dev eth0 onlink 
10.6.0.0/24 dev wg0 proto kernel scope link src 10.6.0.1 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.18.0.0/16 dev br-fde72e55cee7 proto kernel scope link src 172.18.0.1 
192.168.100.0/24 dev eth0 proto kernel scope link src 192.168.100.61 
```

## Attempted Fix(es)

I've tried with and without LAN variable. And I have tried the haugene/transmission-openvpn container getting same results.

Changed provider location, changed to TPC configs.... nothing helps

Is it a bug? if not, what can I do to fix this?

**Comment by friki67** [comment]
The problem was I was accessing through an VPN. I needed add the VPN ip range to the LAN variable to access it. FIXED

**Comment by qu4542** [comment]
i have the same issue, with alpine-qbittorrent-openvpn as well as with tran smission+openvpn docker... i cant seem to figure out the correct LOCALNETWORK= settings
