### ISSUE TITLE
bug : qbittorrent-nox-static release url format has changed

### ISSUE THREAD

**Issue by userdocs** [guillaumedsde/alpine-qbittorrent-openvpn#77]
When I added cross building for armhf and armv7 [I also changed the URL format.](https://github.com/userdocs/qbittorrent-nox-static/releases/tag/release-4.3.5_v1.2.14)

**edit:** Since I also updated some older releases including https://github.com/userdocs/qbittorrent-nox-static/releases/tag/release-4.3.5_v2.0.3

Which will break this.

https://github.com/guillaumedsde/alpine-qbittorrent-openvpn/blob/master/rootfs/usr/sbin/install_qbittorrent.sh#L16

It's basically reversed.

```
aarch64-qbittorrent-nox
```

Also this would work if you only want the latest release ((libtorrent version v1) instead of a specific version

https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/aarch64-qbittorrent-nox

**Comment by guillaumedsde** [comment]
Hi @userdocs thanks for notifying, I've updated the URL format, thanks for the time you spend maintaining these static builds they are very much appreciated :)
