### ISSUE TITLE
s6-svscan panicked! Dropping to a root shell.

### ISSUE THREAD

**Issue by Manichee** [guillaumedsde/alpine-qbittorrent-openvpn#82]
## Information
Unable to get the latest version to run with error:

alpine-qbittorrent-openvpn_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
alpine-qbittorrent-openvpn_1  | [s6-init] ensuring user provided files have correct perms...s6-svscan: warning: unable to iopause: Invalid argument
alpine-qbittorrent-openvpn_1  | s6-svscan: warning: executing into .s6-svscan/crash
alpine-qbittorrent-openvpn_1  | s6-svscan panicked! Dropping to a root shell.
alpine-qbittorrent-openvpn_1  |
alpine-qbittorrent-openvpn_1  | /bin/sh: can't access tty; job control turned off
alpine-qbittorrent-openvpn_1  | /run/s6/services #

If i revert back to dd4cd24 everything works as it used to.

## Current setup
uname -a
Linux raspberrypi 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux

:~ $ cat /etc/*release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

~ $ docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:38 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:53:31 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

This is on a Raspberry pi 4B.

This may or may not be related. https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/36

**Comment by guillaumedsde** [comment]
Hi,  I've updated Alpine to 3.14, could you try again see if it is fixed?

**Comment by guillaumedsde** [comment]
good to hear, sorry for the bother 🙂
